import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Heading from "@/components/Heading/Heading";
import Navbar from "@/components/Navbar/Navbar";
import Categories from "@/components/Categories/Categories";
import Product from "@/components/Product/Product";
import Footer from "@/components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Heading/>
        <Navbar/>
        <Categories/>
        <Product/>
        <Footer/>
        {children}
      </body>
    </html>
  );
}
